---
name: Tests
"on": [push]

permissions: read-all

jobs:
  mega-lint:
    name: Mega Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mega Linter
        uses: megalinter/megalinter/flavors/go@v9.2.0
        env:
          # VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # Validates all source when push on main, else just the git diff with main. Override with true if you always want to lint all sources
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_LINTERS: SPELL_CSPELL
          GO_GOLANGCI_LINT_CLI_LINT_MODE: project
          GO_REVIVE_CLI_LINT_MODE: project
