---
name: Tests
'on': [push]

jobs:
  super-lint:
    name: GitHub Super Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super Linter
        # This makes it pull from github's docker repo according to a note in
        # the README.md
        uses: docker://github/super-linter:v3
        env:
          # super-linter runs golangci-lint in a stupid way, just disable it
          # and run it separately below
          VALIDATE_GO: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci-lint:
    name: golangci-lint on push
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be
          # specified without patch version: we always use the latest patch
          # version.
          version: v1.27
